import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

export const telegramMessages = sqliteTable('telegram_messages', {
    updateId: integer('update_id').primaryKey(),
    messageId: integer('message_id'),
    userId: integer('user_id'),
    firstName: text('first_name'),
    username: text('username'),
    senderChatId: text('sender_chat_id'),
    senderChatTitle: text('sender_chat_title'),
    senderChatUsername: text('sender_chat_username'),
    senderChatType: text('sender_chat_type'),
    chatId: text('chat_id'),
    chatTitle: text('chat_title'),
    chatUsername: text('chat_username'),
    chatType: text('chat_type'),
    date: integer('date'),
    messageThreadId: integer('message_thread_id'),
    replyToMessageId: integer('reply_to_message_id'),
    replyFromId: integer('reply_from_id'),
    replyFromFirstName: text('reply_from_first_name'),
    replySenderChatId: integer('reply_sender_chat_id'),
    replySenderChatTitle: text('reply_sender_chat_title'),
    replySenderChatType: text('reply_sender_chat_type'),
    replyDate: integer('reply_date'),
    forwardFromChatId: integer('forward_from_chat_id'),
    forwardFromChatTitle: text('forward_from_chat_title'),
    forwardFromChatType: text('forward_from_chat_type'),
    forwardFromMessageId: integer('forward_from_message_id'),
    mediaGroupId: integer('media_group_id'),
    photoFileId: text('photo_file_id'),
    caption: text('caption'),
    text: text('text'),
});
